// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_KV: KVNamespace;
	ENVIRONMENT: string;
	APP_URL: string;
	SESSION_SECRET: string;
	HONEYPOT_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	RESEND_API_KEY: string;
	DB: D1Database;
}
